name: Deploy site from main branch 

on:
  push:
    branches:
      - main  # Runs when you push to main
  workflow_dispatch:  # Allows manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Make sure this generates files in ./dist

      - name: Deploy to Main Branch
        run: |
          mkdir -p public
          mv dist/* public/
          touch public/.nojekyll  # Prevents Jekyll from interfering
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add public
          git commit -m "Deploy site"
          git push origin main
