name: Deploy site from main branch 

on:
  push:
    branches:
      - main  # Runs when you push to main
  workflow_dispatch:  # Allows manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install  # Change this if you use yarn/pnpm

      - name: Build Project
        run: npm run build  # Make sure this generates your output folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Change this to your build output folder
